build:
  verbosity: detailed

build_script:
  - cmd: .\gradlew.bat assemble --no-daemon

test_script:
  - cmd: .\gradlew.bat check --no-daemon -Ptest.gradle-versions=3.3

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

on_success:
  - cmd: if exist "%USERPROFILE%\.gradle\caches\modules-2\modules-2.lock" del /Q "%USERPROFILE%\.gradle\caches\modules-2\modules-2.lock"
  - cmd: for /D %%d in ("%USERPROFILE%\.gradle\caches\*") do if exist "%%d\plugin-resolution" rmdir /S /Q "%%d\plugin-resolution"
cache:
  - '%USERPROFILE%\.gradle\caches -> build.gradle'
  - '%USERPROFILE%\.gradle\wrapper -> gradle\wrapper\gradle-wrapper.properties'
 
